services:
  extractor:
    build:
      context: ./extractor
    volumes:
      - ./extractor:/app
    environment:
      - ENV=development
    env_file:
      - ./extractor/.env
    depends_on:
      - postgres
    networks:
      - eras-network

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8502:8501"
    depends_on:
      - postgres
    networks:
      - eras-network

  dashboard_v2:
    build:
      context: ./dashboard_v2
    ports:
      - "8511:8501"
    depends_on:
      - postgres
    networks:
      - eras-network

  postgres:
    image: postgres:15
    env_file:
      - ./extractor/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eras-network

networks:
  eras-network:
    driver: bridge

volumes:
  postgres_data:
