services:
  extractor:
    build:
      context: ./extractor
    environment:
      - ENV=production
    env_file:
      - ./extractor/.env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - eras-network
    restart: unless-stopped
    profiles:
      - extractor

  dashboard:
    build:
      context: ./dashboard
    env_file:
      - ./dashboard/.env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "0.0.0.0:8502:8501"
    networks:
      - eras-network
    restart: unless-stopped

networks:
  eras-network:
    driver: bridge
