services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - ENV=development
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - eras-network

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eras-network

networks:
  eras-network:
    driver: bridge

volumes:
  postgres_data: